export const SYSTEM_FONTS = [
  'Arial',
  'Arial Black',
  'Arial Narrow',
  'Calibri',
  'Cambria',
  'Cambria Math',
  'Comic Sans MS',
  'Consolas',
  'Courier',
  'Courier New',
  'Georgia',
  'Helvetica',
  'Impact',
  'Lucida Console',
  'Lucida Sans Unicode',
  'Microsoft Sans Serif',
  'Monaco',
  'Palatino Linotype',
  'Segoe UI',
  'Tahoma',
  'Times',
  'Times New Roman',
  'Trebuchet MS',
  'Verdana',
  'Noto Sans SC',
  'Noto Serif SC',
  'PingFang SC',
  'PingFang TC',
  'Microsoft YaHei',
  'SimHei',
  'SimSun',
  'STSong',
  'WenQuanYi Micro Hei',
  'Droid Sans Fallback',
  'San Francisco',
  'Segoe UI Emoji',
  'Segoe UI Symbol',
  'Apple Symbols',
  'Symbol',
  'Webdings',
  'Wingdings'
] as const;

export type FontName = typeof SYSTEM_FONTS[number];

export const DEFAULT_FONTS = [
  'SansSerif',
  'Serif',
  'Monospaced'
] as const;
